[workspace]
workspace.resolver = "2"
members = [
    "1_concepts",
    "1_concepts/1_*",
    "2_idioms",
    "2_idioms/2_*",
    "3_ecosystem",
    "3_ecosystem/3_*",
    "3_ecosystem/3_2_macro/btreee_function_macro",
    "4_backend",
    "4_backend/4_*",
    "4_backend/4_2_http/api"
]
