[package]
name = "step_3_7"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8.5"
thiserror = "1.0.47"
ring = "0.17.0-alpha.11"
base64 = "0.21.2"
sha256 = "1.3.0"
rust-argon2 = "2.0.0"
